# This reads in the data generated by the BuildTable.R to set up the dataset to use in Shiny
# Eventually this will be modified to include the relevant sql query
#
# debug average mission response for rate map (Avg members per call not per week)
# 
#
# to run: 
#   setwd("D:/Google Drive/RMR/Response Statistics/Stats Dashboard/Final Dashboard")
#   runApp()
library(RMySQL)

library(shiny)
library(ggplot2)
library(scales)
library(reshape2)
library(plyr)
library(grid)

# this info will need to be corrected for the database
mydb <- dbConnect(MySQL(),
                  user='root', 
                  password='insecure', 
                  dbname='rmrgmaster',
                  host='localhost')

# good reference for queries:
# http://www.r-bloggers.com/accessing-mysql-through-r/

dbListTables(mydb)

##### START QUERY FOR OPERATIONS DATA #####
q1 = dbSendQuery(mydb, 
                 'SELECT operation.DATETIME,operation.type,operation.subtype,operation.opnumber,operation.YEAR,SUM(operationalPeriod.hours) AS hours,operation.idx 
                  FROM operation
                  INNER JOIN operationalPeriod ON operation.idx = operationalPeriod.operationIdx
                  WHERE operation.DATETIME IS NOT NULL
                  GROUP BY operation.idx')

operationsdata = fetch(q1, n=-1)  

#write.csv(operationsdata,"operationsdata_debug.csv")
# converts dates from strings
operationsdata$DATETIME=as.POSIXct(operationsdata$DATETIME)
operationsdata$YEAR=as.POSIXct(operationsdata$YEAR)

##### END QUERY FOR OPERATIONS DATA #####

##### START QUERY FOR OPERATIONS ATTENDANCE DATA #####
q2 = dbSendQuery(mydb, 
                 'SELECT FirstName,LastName,currentRankIdx,operationalPeriod.DATETIME,operationalPeriod.hours,operation.type,operation.subtype,operation.opnumber,operation.YEAR  
                  FROM opattendance
                  INNER JOIN operationalPeriod ON opattendance.opPeriodIdx = operationalPeriod.idx
                  INNER JOIN member ON opattendance.memberIdx = member.idx
                  INNER JOIN operation ON operationalPeriod.operationIdx = operation.idx
                  WHERE operation.DATETIME IS NOT NULL')

opattdata = fetch(q2, n=-1)  
#write.csv(opattdata,"opattdata_debug.csv")

# converts dates from strings
opattdata$DATETIME=as.POSIXct(opattdata$DATETIME)
opattdata$YEAR=as.POSIXct(opattdata$YEAR)


##### START QUERY FOR OPERATIONS ATTENDANCE DATA #####

##### START PREPROCESSING OPERATIONS DATA #####

# add in day of year
cn = colnames(operationsdata)
operationsdata = cbind(operationsdata,as.numeric(as.Date(operationsdata$DATETIME)-as.Date(operationsdata$YEAR)+1))
colnames(operationsdata) = c(cn,"DOY") 

# add in weekday
weekdays = data.frame(wd=as.character(as.POSIXlt(operationsdata$DATETIME)$wday))
wd.code = c("Sun"=0,"Mon"=1,"Tues"=2,"Wed"=3,"Thurs"=4,"Fri"=5,"Sat"=6)
match.idx <- match(weekdays$wd, wd.code)

weekdays$name <- ifelse(is.na(match.idx),
                        weekdays$wd,
                        names(wd.code)[match.idx])

weekdays$name = factor(weekdays$name,names(wd.code))
# weekdays<-factor(weekdays$)

cn = colnames(operationsdata)

operationsdata = cbind(operationsdata,weekdays$name)
colnames(operationsdata) = c(cn,"Weekday") 

# add in hour
cn = colnames(operationsdata)
operationsdata = cbind(operationsdata,as.character(as.POSIXlt(operationsdata$DATETIME)$hour))
colnames(operationsdata) = c(cn,"Hour") 
operationsdata$Hour = factor(operationsdata$Hour,as.character(rev(seq(0,23))))

##### END PREPROCESSING OPERATIONS DATA #####


##### START PREPROCESSING OPERATIONS ATTENDANCE DATA #####

# add in day of year
cn = colnames(opattdata)
opattdata = cbind(opattdata,as.numeric(as.Date(opattdata$DATETIME)-as.Date(opattdata$YEAR)+1))
colnames(opattdata) = c(cn,"DOY") 

# add in weekday
weekdays = data.frame(wd=as.character(as.POSIXlt(opattdata$DATETIME)$wday))
wd.code = c("Sun"=0,"Mon"=1,"Tues"=2,"Wed"=3,"Thurs"=4,"Fri"=5,"Sat"=6)
match.idx <- match(weekdays$wd, wd.code)

weekdays$name <- ifelse(is.na(match.idx),
                            weekdays$wd,
                            names(wd.code)[match.idx])

weekdays$name = factor(weekdays$name,names(wd.code))

cn = colnames(opattdata)

opattdata = cbind(opattdata,weekdays$name)
colnames(opattdata) = c(cn,"Weekday") 

# add in hour
cn = colnames(opattdata)
opattdata = cbind(opattdata,as.character(as.POSIXlt(opattdata$DATETIME)$hour))
colnames(opattdata) = c(cn,"Hour") 
opattdata$Hour = factor(opattdata$Hour,as.character(rev(seq(0,23))))

##### END PREPROCESSING OPERATIONS ATTENDANCE DATA #####
