# This reads in the data generated by the BuildTable.R to set up the dataset to use in Shiny
# Eventually this will be modified to include the relevant sql query
setwd("D:/Google Drive/RMR/Response Statistics/Stats Dashboard")

# Operations only
operationsdata = read.csv("operations.csv")


# add in day of year
cn = colnames(operationsdata)
operationsdata = cbind(operationsdata,as.numeric(as.Date(operationsdata$DATETIME)-as.Date(operationsdata$YEAR)+1))
colnames(operationsdata) = c(cn,"DOY") 

# add in weekday
weekdays = data.frame(wd=as.character(as.POSIXlt(operationsdata$DATETIME)$wday))
wd.code = c("Sun"=0,"Mon"=1,"Tues"=2,"Wed"=3,"Thurs"=4,"Fri"=5,"Sat"=6)
match.idx <- match(weekdays$wd, wd.code)

weekdays$name <- ifelse(is.na(match.idx),
                        weekdays$wd,
                        names(wd.code)[match.idx])

weekdays$name = factor(weekdays$name,names(wd.code))
# weekdays<-factor(weekdays$)

cn = colnames(operationsdata)

operationsdata = cbind(operationsdata,weekdays$name)
colnames(operationsdata) = c(cn,"Weekday") 

# add in hour
cn = colnames(operationsdata)
operationsdata = cbind(operationsdata,as.character(as.POSIXlt(operationsdata$DATETIME)$hour))
colnames(operationsdata) = c(cn,"Hour") 
operationsdata$Hour = factor(operationsdata$Hour,as.character(rev(seq(0,23))))



# Operational Periods
opattdata = read.csv("opattendance.csv")

# add in day of year
cn = colnames(opattdata)
opattdata = cbind(opattdata,as.numeric(as.Date(opattdata$DATETIME)-as.Date(opattdata$YEAR)+1))
colnames(opattdata) = c(cn,"DOY") 

# add in weekday
weekdays = data.frame(wd=as.character(as.POSIXlt(opattdata$DATETIME)$wday))
wd.code = c("Sun"=0,"Mon"=1,"Tues"=2,"Wed"=3,"Thurs"=4,"Fri"=5,"Sat"=6)
match.idx <- match(weekdays$wd, wd.code)

weekdays$name <- ifelse(is.na(match.idx),
                            weekdays$wd,
                            names(wd.code)[match.idx])

weekdays$name = factor(weekdays$name,names(wd.code))
# weekdays<-factor(weekdays$)

cn = colnames(opattdata)

opattdata = cbind(opattdata,weekdays$name)
colnames(opattdata) = c(cn,"Weekday") 

# add in hour
cn = colnames(opattdata)
opattdata = cbind(opattdata,as.character(as.POSIXlt(opattdata$DATETIME)$hour))
colnames(opattdata) = c(cn,"Hour") 
opattdata$Hour = factor(opattdata$Hour,as.character(rev(seq(0,23))))

# opattdata[1:5,]

